{% set name = "pygtail" %}
{% set version = "0.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/14/e9/9453197f05346ae80b68ecc321ff553b59365881a61502c5001e6c6f9e6f/pygtail-0.11.0.tar.gz
  md5: 7c6edad774bf221ec6b5e22804d55b58

build:
  skip: True  # [win]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - pygtail -h

about:
    home: https://github.com/bgreenlee/pygtail
    license: GPL-2
    license_family: GPL
    license_file: LICENSE
    summary: A python 'port' of logcheck’s logtail2

extra:
    recipe-maintainers:
        - tsenapathi
